name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: 3 in 1
              run: |
                echo "My First Github Acitons Job"
                ls
                cat README.md