name: Generate ASCII
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install Cowsay Program
              run: sudo apt install cowsay -y
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Hi there im Dragon. ahha!" >> dragon.txt
            - name: List files
              run: ls -ltra
            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
            - name: Display the Content
              run: cat dragon.txt
    
