name: Multi Job
on: push

jobs:
    Build_Job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt install cowsay -y
            
            - name: Execute Cowsay
              run: cowsay -f dragon "Hi there im Dragon. ahha!" >> dragon.txt

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file-txt
                path: dragon.txt
    
    Test_Job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file-txt
            
            - name: Test File
              run: grep -i "dragon" dragon.txt

    Deploy_Job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file-txt
            
            - name: Read Dragon
              run: cat dragon.txt

            - name: Deploy Dragon
              run: echo "Deploying Dragon..."
    